version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./hh-ai/build:/home/ubuntu/react-flask-app/build
      - ./proxy_params:/etc/nginx/proxy_params
    depends_on:
      - react
      - flask

  react:
    build:
      context: ./hh-ai
      dockerfile: Dockerfile
    container_name: react
#################    restart: always
    volumes:
      - ./hh-ai:/app
    working_dir: /app
    command: sh -c "yarn install && yarn build && serve -s build"

  flask:
    build:
      context: ./flask-ollama-proxy
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    volumes:
      - ./flask-ollama-proxy:/app
    working_dir: /app
    command: sh -c "./entrypoint.sh"
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
